---
- name: "{{ service_name }} | setup | env | Include default config"
  include_tasks: "{{ role_path }}/tasks/setup/env/main.yaml"

- name: "{{ service_name }} | setup | env | Set AdServer's base URI"
  ansible.builtin.lineinfile:
    path: "{{ service_dir }}-init/{{ service_env_file_local }}"
    regexp: '^ADSERVER_BASE_URI='
    line: "ADSERVER_BASE_URI=\"https://{{ adserver_prefix }}.{{ server_domain }}\""

- name: "{{ service_name }} | setup | env | Set web application public URL (serve path)"
  ansible.builtin.lineinfile:
    path: "{{ service_dir }}-init/{{ service_env_file_local }}"
    regexp: '^PUBLIC_HOST='
    line: "PUBLIC_HOST=\"{{ adpanel_prefix }}.{{ server_domain }}\""

- name: "{{ service_name }} | setup | env | Set web application public URL (serve path)"
  ansible.builtin.lineinfile:
    path: "{{ service_dir }}-init/{{ service_env_file_local }}"
    regexp: '^PUBLIC_PORT='
    line: "PUBLIC_PORT=\"80\""

- name: "{{ service_name }} | setup | env | Set web application public URL (serve path)"
  ansible.builtin.lineinfile:
    path: "{{ service_dir }}-init/{{ service_env_file_local }}"
    regexp: '^PUBLIC_PATH='
    line: "PUBLIC_PATH=\"{{ adcontroller_public_path }}\""
