---
- name: "{{ service_name }} | setup | cron | add ops:targeting-options:update"
  cron:
    name: "{{ service_name }} | ops:targeting-options:update"
    minute: "12"
    job: "php {{ service_dir }}/artisan ops:targeting-options:update"
  become_user: "{{ service_user }}"
  become: true

- name: "{{ service_name }} | setup | cron | add ops:filtering-options:update"
  cron:
    name: "{{ service_name }} | ops:filtering-options:update"
    minute: "12"
    job: "php {{ service_dir }}/artisan ops:filtering-options:update"
  become_user: "{{ service_user }}"
  become: true

- name: "{{ service_name }} | setup | cron | add ops:statistics:backup"
  cron:
    name: "{{ service_name }} | ops:statistics:backup"
    minute: "11"
    hour: "2"
    job: "php {{ service_dir }}/artisan ops:statistics:backup"
  become_user: "{{ service_user }}"
  become: true

- name: "{{ service_name }} | setup | cron | add delete old reports"
  cron:
    name: "{{ service_name }} | delete old reports"
    minute: "10"
    hour: "2"
    job: "find {{ service_dir }}/storage/app/public -maxdepth 1 -type f -name '*.csv' -mtime +10 -delete"
  become_user: "{{ service_user }}"
  become: true

- name: "{{ service_name }} | setup | cron | add ops:exchange-rate:fetch"
  cron:
    name: "{{ service_name }} | ops:exchange-rate:fetch"
    minute: "0-5,10"
    job: "php {{ service_dir }}/artisan ops:exchange-rate:fetch"
  become_user: "{{ service_user }}"
  become: true

- name: "{{ service_name }} | setup | cron | add ops:demand:inventory:import"
  cron:
    name: "{{ service_name }} | ops:demand:inventory:import"
    minute: "*/10"
    job: "php {{ service_dir }}/artisan ops:demand:inventory:import >/dev/null && php {{ service_dir }}/artisan ops:adselect:inventory:export >/dev/null"
  become_user: "{{ service_user }}"
  become: true

- name: "{{ service_name }} | setup | cron | add ops:adselect:case:export"
  cron:
    name: "{{ service_name }} | ops:adselect:case:export"
    job: "php {{ service_dir }}/artisan ops:adselect:case:export >/dev/null"
  become_user: "{{ service_user }}"
  become: true

- name: "{{ service_name }} | setup | cron | add ops:adpay:campaign:export"
  cron:
    name: "{{ service_name }} | ops:adpay:campaign:export"
    job: "php {{ service_dir }}/artisan ops:adpay:campaign:export >/dev/null && php {{ service_dir }}/artisan ops:adpay:event:export -t 6 2>&1"
  become_user: "{{ service_user }}"
  become: true

- name: "{{ service_name }} | setup | cron | add ops:expired-withdrawal:cancel"
  cron:
    name: "{{ service_name }} | ops:expired-withdrawal:cancel"
    job: "php {{ service_dir }}/artisan ops:expired-withdrawal:cancel >/dev/null"
  become_user: "{{ service_user }}"
  become: true

- name: "{{ service_name }} | setup | cron | add ops:demand:payments:process"
  cron:
    name: "{{ service_name }} | ops:demand:payments:process"
    minute: "15-20,25-59/5"
    job: "php {{ service_dir }}/artisan ops:demand:payments:process > /dev/null"
  become_user: "{{ service_user }}"
  become: true

- name: "{{ service_name }} | setup | cron | add ops:demand:payments:block"
  cron:
    name: "{{ service_name }} | ops:demand:payments:block"
    minute: "59"
    job: "php {{ service_dir }}/artisan ops:demand:payments:block"
  become_user: "{{ service_user }}"
  become: true

- name: "{{ service_name }} | setup | cron | add ads:process-tx"
  cron:
    name: "{{ service_name }} | ads:process-tx"
    minute: "1-59/5"
    job: "php {{ service_dir }}/artisan ads:process-tx > /dev/null"
  become_user: "{{ service_user }}"
  become: true

- name: "{{ service_name }} | setup | cron | add ops:supply:payments:process"
  cron:
    name: "{{ service_name }} | ops:supply:payments:process"
    minute: "1-59/12"
    job: "php {{ service_dir }}/artisan ops:supply:payments:process > /dev/null && php {{ service_dir }}/artisan ops:adselect:case-payments:export > /dev/null  && php {{ service_dir }}/artisan ops:wallet:withdrawal:check > /dev/null && php {{ service_dir }}/artisan ops:stats:aggregate:publisher > /dev/null"
  become_user: "{{ service_user }}"
  become: true

- name: "{{ service_name }} | setup | cron | add ops:demand:classification:request"
  cron:
    name: "{{ service_name }} | ops:demand:classification:request"
    minute: "*/5"
    job: "php {{ service_dir }}/artisan ops:demand:classification:request"
  become_user: "{{ service_user }}"
  become: true

- name: "{{ service_name }} | setup | cron | add ops:supply:site-rank:update"
  cron:
    name: "{{ service_name }} | ops:supply:site-rank:update"
    minute: "0-45/5,55"
    job: "php {{ service_dir }}/artisan ops:supply:site-rank:update"
  become_user: "{{ service_user }}"
  become: true

- name: "{{ service_name }} | setup | cron | add ops:supply:site-rank:update all"
  cron:
    name: "{{ service_name }} | ops:supply:site-rank:update"
    minute: "50"
    job: "php {{ service_dir }}/artisan ops:supply:site-rank:update --all"
  become_user: "{{ service_user }}"
  become: true

- name: "{{ service_name }} | setup | cron | add ops:supply:site-rank:reassess"
  cron:
    name: "{{ service_name }} | ops:supply:site-rank:reassess"
    minute: "54"
    hour: "18"
    job: "php {{ service_dir }}/artisan ops:supply:site-rank:reassess"
  become_user: "{{ service_user }}"
  become: true

- name: "{{ service_name }} | setup | cron | add ops:license:fetch"
  cron:
    name: "{{ service_name }} | ops:license:fetch"
    minute: "0"
    hour: "0"
    job: "php {{ service_dir }}/artisan ops:license:fetch"
  become_user: "{{ service_user }}"
  become: true

- name: "{{ service_name }} | setup | cron | add ops:serve-domains:update"
  cron:
    name: "{{ service_name }} | ops:serve-domains:update"
    minute: "0"
    hour: "0"
    job: "php {{ service_dir }}/artisan ops:serve-domains:update"
  become_user: "{{ service_user }}"
  become: true

- name: "{{ service_name }} | setup | cron | add ops:wallet:transfer:cold"
  cron:
    name: "{{ service_name }} | ops:wallet:transfer:cold"
    minute: "*/30"
    job: "php {{ service_dir }}/artisan ops:wallet:transfer:cold && php {{ service_dir }}/artisan ops:wallet:transfer:check"
  become_user: "{{ service_user }}"
  become: true

- name: "{{ service_name }} | setup | cron | add ads:broadcast-host"
  cron:
    name: "{{ service_name }} | ads:broadcast-host"
    minute: "0"
    hour: "*/12"
    job: "php {{ service_dir }}/artisan ads:broadcast-host"
  become_user: "{{ service_user }}"
  become: true

- name: "{{ service_name }} | setup | cron | add ads:fetch-hosts"
  cron:
    name: "{{ service_name }} | ads:fetch-hosts"
    minute: "30"
    hour: "*/6"
    job: "php {{ service_dir }}/artisan ads:fetch-hosts"
  become_user: "{{ service_user }}"
  become: true

- name: "{{ service_name }} | setup | cron | add ops:events:clear"
  cron:
    name: "{{ service_name }} | ops:events:clear"
    minute: "50"
    hour: "*/1"
    job: "php {{ service_dir }}/artisan ops:events:clear --period=P10D"
  become_user: "{{ service_user }}"
  become: true

- name: "{{ service_name }} | setup | cron | add ops:targeting-reach:compute"
  cron:
    name: "{{ service_name }} | ops:targeting-reach:compute"
    minute: "35"
    hour: "3"
    job: "php {{ service_dir }}/artisan ops:targeting-reach:compute"
  become_user: "{{ service_user }}"
  become: true

- name: "{{ service_name }} | setup | cron | add ops:targeting-reach:fetch"
  cron:
    name: "{{ service_name }} | ops:targeting-reach:fetch"
    minute: "45"
    hour: "*/3"
    job: "php {{ service_dir }}/artisan ops:targeting-reach:fetch"
  become_user: "{{ service_user }}"
  become: true

- name: "{{ service_name }} | setup | cron | add ops:reports:clear"
  cron:
    name: "{{ service_name }} | ops:reports:clear"
    minute: "45"
    hour: "2"
    job: "php {{ service_dir }}/artisan ops:reports:clear"
  become_user: "{{ service_user }}"
  become: true

- name: "{{ service_name }} | setup | cron | add ops:demand:cdn:upload"
  cron:
    name: "{{ service_name }} | ops:demand:cdn:upload"
    minute: "*/5"
    job: "php {{ service_dir }}/artisan ops:demand:cdn:upload"
  become_user: "{{ service_user }}"
  become: true
