- name: "{{ service_name }} | config | Reset config"
  ansible.builtin.include_vars:
    file: "../vars/main.yaml"

- name: "{{ service_name }} | config | Load config"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files: ["{{ service_name }}.yaml"]
      skip: true
