---
- name: "{{ service_name }} | deploy | jwt | Get AdServer's public key"
  ansible.builtin.copy:
    src: "{{ vendor_dir }}/adserver/config/jwt/oauth-public.key"
    dest: "{{ service_dir }}/config/jwt/oauth-public.key"
    remote_src: true
    owner: "{{ service_user }}"
    group: "{{ service_user }}"
    mode: "0644"
  when: copy_jwt
